### ISSUE TITLE
ChiMerge.py

### ISSUE THREAD

**Issue by AlinaLei** [Lantianzz/Scorecard-Bundle#2]
the usage of np.quantile is not correct, you may use np.percentile or df[x].quantile

**Comment by Lantianzz** [comment]
Hi, I'm so sorry that I saw this message nearly a month later. `np.quantile` and `np.percentile` are equivalent. The only difference is that the `q` parameter np.quantile is in  range [0, 1], while the one in np.percentile is in range [0, 100]. See details in https://docs.scipy.org/doc/numpy/reference/generated/numpy.quantile.html

![image](https://user-images.githubusercontent.com/32934889/78465529-5fa16a80-7729-11ea-982b-be5c080fe3b1.png)

**Comment by AlinaLei** [comment]
thanks for your reply,the version for numpy that I used is too low that encounted the attributeerror,when I test np.quantile in numpy of version 1.18+ is ok.
