### ISSUE TITLE
卡方分箱不能处理缺失值吗

### ISSUE THREAD

**Issue by Blanket58** [Lantianzz/Scorecard-Bundle#3]
如题，有缺失值的变量运行就会出错

**Comment by Lantianzz** [comment]
你好，ScorecardBundle的功能是不包括处理缺失值的，卡方分箱的fit()的输入需要是数值型（连续型变量或者经过编码的离散型变量）。没有加入缺失值处理功能的原因有2个：

1)  缺失值处理方法视具体场景而异，连续型变量赋值为最小值、最大值、0、中位数、平均数、-1均比较常见，通常要看特征的实际含义和分布决定；离散型变量通常的做法是赋值"缺失"然后跟其他标签一起进行编码，编码包括直接编码1-n、独热编码、根据预测力等指标排序后编码等方法（二分类问题中根据响应率编码效果很好）。上述缺失值处理基于pandas的fillna和sklearn的preprocessing模块可以很便捷的实现。

2）ScorecardBundle在使用方法上对标的是sklearn，因此输入的数据跟sklearn一样，必须是数值型（支持pandas.DataFrame和numpy.ndarray）
·

**Comment by Blanket58** [comment]
谢谢这么快的回复！我的问题其实是：数值型变量在进行卡方分箱时，如果想把缺失值单独分箱的话，就没有办法操作了呀

**Comment by Lantianzz** [comment]
可以考虑给缺失值赋予一个目前没有的值，比如给一个都为正的特征的缺失值赋值为-1，然后正常训练卡方分箱，得到结果后，使用ChiMerge的assign_interval_str()函数调整分组结果，给缺失值单独分配一个区间即可`new_x = cm.assign_interval_str(X[col].values,[1176,2012,2499,4178])`，完整示例见https://github.com/Lantianzz/Scorecard-Bundle/blob/master/examples/%5BExample%5D%20Build%20a%20scorecard%20with%20high%20explainability%20and%20good%20predictability%20with%20Scorecard-Bundle.ipynb
