### ISSUE TITLE
评分卡ChiMerge的时候，存在结果中不包含inf档位的情况

### ISSUE THREAD

**Issue by zeyunH** [Lantianzz/Scorecard-Bundle#5]
评分卡ChiMerge的时候，存在结果中不包含inf档位的情况。

**Comment by Lantianzz** [comment]
感谢反馈，在V1.2.1版本中已修复。在ChiMerge的fit阶段，当得到的阈值大于等于数据最大值时，会将相应的结果区间的右侧边界改为inf，使fit得到的区间能覆盖-inf~inf的全部值域。而在transform时则会严格按照给定阈值输出区间，不会对区间进行调整
